### ISSUE TITLE
Repo link

### ISSUE THREAD

**Issue by simoneb** [nearform/osscheck#104]
Let's add a link to the github repo somewhere in the UI. No strong opinions about where, although most people usually put it in the navbar, at the far right.

E.g. https://nearform.github.io/initium-website/

**Comment by simoneb** [comment]
@travis-spanu-nearform when you get a chance can you please put together some designs for this?

**Comment by travis-spanu-nearform** [comment]
Added a Github icon to the navigation in the designs which should link to the repo.
