### ISSUE TITLE
Shows no repository when changing the number of repositories to show

### ISSUE THREAD

**Issue by d4nyll** [nearform/osscheck#128]
**Steps to reproduce**:

1. Go to https://nearform.github.io/osscheck/
1. Select **Show 10**
2. Press **Next** to go to the next page
3. Select **Show 60**

<img width="832" alt="Screenshot 2023-09-29 at 15 28 55" src="https://github.com/nearform/osscheck/assets/9997953/35d07822-e231-4942-a03c-a91eb7cadcb9">

**Comment by simoneb** [comment]
Thanks for reporting Daniel

**Comment by alfonsograziano** [comment]
Sorry for the unnecessary assignment, looking on the board it was free. Only when I clicked on it to get more details I saw that we already have a fix for it :)

**Comment by simoneb** [comment]
@ShaunBaker to prevent this from happening can you please assign issues to yourself when you pick them up? Thanks
