### ISSUE TITLE
UI - Max Width

### ISSUE THREAD

**Issue by travis-spanu-nearform** [nearform/osscheck#140]

**Comment by travis-spanu-nearform** [comment]
**Current**

Max Width  80rem



![Image](https://github.com/nearform/osscheck/assets/140637671/e4e0e519-2d68-410b-b73f-669e4b340c1c)

**Expected**

Max Width 90rem



![Image](https://github.com/nearform/osscheck/assets/140637671/9a531572-672f-42ff-aea7-2a2caed63fa0)

**Comment by ShaunBaker** [comment]
This defect does not take into account devices with a smaller viewport than 1440px appropriately.

For example, on a device (Macbook 13 inch) a setting of 90rem fills the whole viewport width - without any side padding.

As such the main container behaves as follows:

'lg': '1024px' -> max-w-5xl (66rem) => 1056px
'xl': '1280px' -> max-w-7xl (80rem) => 1280px
'2xl': '1536px' -> max-w-8xl (90rem) => 1440px
